package com.rufeng.business.system.service.impl;


import java.util.List;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;

import com.rufeng.core.framework.db.Pager;
import com.rufeng.core.framework.web.ResultData;
import com.rufeng.business.system.service.ISysNoticeService;
import com.rufeng.business.system.mapper.ISysNoticeDao;
import com.rufeng.business.system.domain.po.SysNotice;


/**
 * 通知公告 服务接口实现
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@Service
public class SysNoticeServiceImpl extends ServiceImpl<ISysNoticeDao, SysNotice> implements ISysNoticeService {
    private Logger log = LoggerFactory.getLogger(SysNoticeServiceImpl.class);

    @Autowired
    private ISysNoticeDao sysnoticeDao;

    @Override
    public ResultData get(String noticeid) throws Exception {
        log.debug("###[服务] 开始查询通知公告 noticeid=[{}]. ", noticeid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        SysNotice sysnotice = sysnoticeDao.selectById(noticeid);
        resData.setData("sysnotice", sysnotice);
        log.info("###[服务] 完成查询通知公告 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData find(SysNotice sysnotice) throws Exception {
        log.debug("###[服务] 开始根据条件{}查询通知公告", sysnotice);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        QueryWrapper<SysNotice> sysnoticeWrapper = new QueryWrapper<>();
        sysnoticeWrapper.setEntity(sysnotice);
        List<SysNotice> sysnotices = sysnoticeDao.selectList(sysnoticeWrapper);
        resData.setData("sysnotices", sysnotices);
        log.info("###[服务] 完成查询通知公告 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData listPager(SysNotice sysnotice, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询通知公告", sysnotice);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        Page<SysNotice> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysNotice> sysnoticeWrapper = new QueryWrapper<>();
        sysnoticeWrapper.setEntity(sysnotice);
        IPage<SysNotice> pu = sysnoticeDao.selectPage(pageParam, sysnoticeWrapper);
        resData.setData("data", pu);

        log.info("###[服务] 完成分页查询通知公告 resData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData add(SysNotice sysnotice) throws Exception {
        log.debug("###[服务] 开始添加新通知公告, {}", sysnotice);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int inserted = sysnoticeDao.insert(sysnotice);
        resData.setData("inserted", inserted);
        log.info("###[服务] 完成添加新通知公告，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData update(SysNotice sysnotice) throws Exception {
        log.debug("###[服务] 开始根据条件{}修改通知公告,", sysnotice);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int updated = sysnoticeDao.updateById(sysnotice);
        resData.setData("updated", updated);
        log.info("###[服务] 完成修改通知公告，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData delete(String noticeid) throws Exception {
        log.debug("###[服务] 开始根据条件{}删除通知公告,", noticeid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        SysNotice sysnotice = new SysNotice();
        sysnotice.setNoticeid(Long.valueOf(noticeid));
        int deleted = sysnoticeDao.deleteById(sysnotice);
        resData.setData("deleted", deleted);
        log.info("###[服务] 完成删除通知公告，ResultData=[{}]", resData);
        return resData;
    }
}
