package com.rufeng.business.system.service.impl;


import java.util.List;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;

import com.rufeng.core.framework.db.Pager;
import com.rufeng.core.framework.web.ResultData;
import com.rufeng.business.system.service.ISysOperLogService;
import com.rufeng.business.system.mapper.ISysOperLogDao;
import com.rufeng.business.system.domain.po.SysOperLog;


/**
 * 操作日志记录 服务接口实现
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@Service
public class SysOperLogServiceImpl extends ServiceImpl<ISysOperLogDao, SysOperLog> implements ISysOperLogService {
    private Logger log = LoggerFactory.getLogger(SysOperLogServiceImpl.class);

    @Autowired
    private ISysOperLogDao sysoperlogDao;

    @Override
    public ResultData get(String operid) throws Exception {
        log.debug("###[服务] 开始查询操作日志记录 operid=[{}]. ", operid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        SysOperLog sysoperlog = sysoperlogDao.selectById(operid);
        resData.setData("sysoperlog", sysoperlog);
        log.info("###[服务] 完成查询操作日志记录 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData list(SysOperLog sysoperlog) throws Exception {
        log.debug("###[服务] 开始根据条件{}查询操作日志记录", sysoperlog);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        QueryWrapper<SysOperLog> sysoperlogWrapper = new QueryWrapper<>();
        sysoperlogWrapper.setEntity(sysoperlog);
        List<SysOperLog> sysoperlogs = sysoperlogDao.selectList(sysoperlogWrapper);
        resData.setData("sysoperlogs", sysoperlogs);
        log.info("###[服务] 完成查询操作日志记录 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData listPager(SysOperLog sysoperlog, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询操作日志记录", sysoperlog);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        Page<SysOperLog> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysOperLog> sysoperlogWrapper = new QueryWrapper<>();
        sysoperlogWrapper.setEntity(sysoperlog);
        IPage<SysOperLog> pu = sysoperlogDao.selectPage(pageParam, sysoperlogWrapper);
        resData.setData("data", pu);
        log.info("###[服务] 完成分页查询操作日志记录 resData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData add(SysOperLog sysoperlog) throws Exception {
        log.debug("###[服务] 开始添加新操作日志记录, {}", sysoperlog);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int inserted = sysoperlogDao.insert(sysoperlog);
        resData.setData("inserted", inserted);
        log.info("###[服务] 完成添加新操作日志记录，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData update(SysOperLog sysoperlog) throws Exception {
        log.debug("###[服务] 开始根据条件{}修改操作日志记录,", sysoperlog);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int updated = sysoperlogDao.updateById(sysoperlog);
        resData.setData("updated", updated);
        log.info("###[服务] 完成修改操作日志记录，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData delete(String operid) throws Exception {
        log.debug("###[服务] 开始根据条件{}删除操作日志记录,", operid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        SysOperLog sysoperlog = new SysOperLog();
        sysoperlog.setOperid(Long.valueOf(operid));
        int deleted = sysoperlogDao.deleteById(sysoperlog);
        resData.setData("deleted", deleted);
        log.info("###[服务] 完成删除操作日志记录，ResultData=[{}]", resData);
        return resData;
    }
}
