package com.rufeng.business.system.service.impl;


import java.util.List;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;

import com.rufeng.core.framework.db.Pager;
import com.rufeng.core.framework.web.ResultData;
import com.rufeng.business.system.service.ISysPostService;
import com.rufeng.business.system.mapper.ISysPostDao;
import com.rufeng.business.system.domain.po.SysPost;


/**
 * 岗位信息 服务接口实现
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@Service
public class SysPostServiceImpl extends ServiceImpl<ISysPostDao,SysPost> implements ISysPostService {
    private Logger log = LoggerFactory.getLogger(SysPostServiceImpl.class);

    @Autowired
    private ISysPostDao syspostDao;

    @Override
    public ResultData get(String post_id) throws Exception {
        log.debug("###[服务] 开始查询岗位信息 post_id=[{}]. ", post_id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        SysPost syspost = syspostDao.selectById(post_id);
        resData.setData("syspost", syspost);
        log.info("###[服务] 完成查询岗位信息 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData list(SysPost syspost) throws Exception {
        log.debug("###[服务] 开始根据条件{}查询岗位信息", syspost);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        QueryWrapper<SysPost> syspostWrapper = new QueryWrapper<>();
        syspostWrapper.setEntity(syspost);
        List<SysPost> sysposts = syspostDao.selectList(syspostWrapper);
        resData.setData("sysposts", sysposts);
        log.info("###[服务] 完成查询岗位信息 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData listPager(SysPost syspost, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询岗位信息", syspost);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        Page<SysPost> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysPost> syspostWrapper = new QueryWrapper<>();
        syspostWrapper.setEntity(syspost);
        IPage<SysPost> pu = syspostDao.selectPage(pageParam, syspostWrapper);
        resData.setData("data", pu);

        log.info("###[服务] 完成分页查询岗位信息 resData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData add(SysPost syspost) throws Exception {
        log.debug("###[服务] 开始添加新岗位信息, {}", syspost);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int inserted = syspostDao.insert(syspost);
        resData.setData("inserted", inserted);
        log.info("###[服务] 完成添加新岗位信息，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData update(SysPost syspost) throws Exception {
        log.debug("###[服务] 开始根据条件{}修改岗位信息,", syspost);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int updated = syspostDao.updateById(syspost);
        resData.setData("updated", updated);
        log.info("###[服务] 完成修改岗位信息，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData delete(String postid) throws Exception {
        log.debug("###[服务] 开始根据条件{}删除岗位信息,", postid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        SysPost syspost = new SysPost();
        syspost.setPostid(Long.valueOf(postid));
        int deleted = syspostDao.deleteById(syspost);
        resData.setData("deleted", deleted);
        log.info("###[服务] 完成删除岗位信息，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public List<SysPost> selectPostAll() {
        QueryWrapper<SysPost> queryWrapper = new QueryWrapper<>();
        List<SysPost> sysPosts = syspostDao.selectList(queryWrapper);
        return sysPosts;
    }

    @Override
    public List<Integer> selectPostListByUserId(Long user_id) {

        return syspostDao.selectPostListByUserId(user_id);
    }
}
