package com.rufeng.business.system.service.impl;


import java.util.List;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;

import com.rufeng.core.framework.db.Pager;
import com.rufeng.core.framework.web.ResultData;
import com.rufeng.business.system.service.ISysRoleMenuService;
import com.rufeng.business.system.mapper.ISysRoleMenuDao;
import com.rufeng.business.system.domain.po.SysRoleMenu;


/**
 * 角色和菜单关联 服务接口实现
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@Service
public class SysRoleMenuServiceImpl extends ServiceImpl<ISysRoleMenuDao, SysRoleMenu> implements ISysRoleMenuService {
    private Logger log = LoggerFactory.getLogger(SysRoleMenuServiceImpl.class);

    @Autowired
    private ISysRoleMenuDao sysrolemenuDao;

    @Override
    public ResultData get(String menuid, String roleid) throws Exception {
        log.debug("###[服务] 开始查询角色和菜单关联 menuid=[{}]. roleid=[{}]. ", menuid, roleid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
//        Map<String, String> param = new HashMap<String, String>();
//        param.put("menuid", menuid);
//        param.put("roleid", roleid);
//        SysRoleMenu sysrolemenu = sysrolemenuDao.get(param);
//        resData.setData("sysrolemenu", sysrolemenu);
        log.info("###[服务] 完成查询角色和菜单关联 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData find(SysRoleMenu sysrolemenu) throws Exception {
        log.debug("###[服务] 开始根据条件{}查询角色和菜单关联", sysrolemenu);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        QueryWrapper<SysRoleMenu> sysrolemenuWrapper = new QueryWrapper<>();
        sysrolemenuWrapper.setEntity(sysrolemenu);
        List<SysRoleMenu> sysrolemenus = sysrolemenuDao.selectList(sysrolemenuWrapper);
        resData.setData("sysrolemenus", sysrolemenus);
        log.info("###[服务] 完成查询角色和菜单关联 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData listPager(SysRoleMenu sysrolemenu, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询角色和菜单关联", sysrolemenu);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        Page<SysRoleMenu> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysRoleMenu> sysrolemenuWrapper = new QueryWrapper<>();
        sysrolemenuWrapper.setEntity(sysrolemenu);
        IPage<SysRoleMenu> pu = sysrolemenuDao.selectPage(pageParam, sysrolemenuWrapper);
        resData.setData("data", pu);

        log.info("###[服务] 完成分页查询角色和菜单关联 resData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData add(SysRoleMenu sysrolemenu) throws Exception {
        log.debug("###[服务] 开始添加新角色和菜单关联, {}", sysrolemenu);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int inserted = sysrolemenuDao.insert(sysrolemenu);
        resData.setData("inserted", inserted);
        log.info("###[服务] 完成添加新角色和菜单关联，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData update(SysRoleMenu sysrolemenu) throws Exception {
        log.debug("###[服务] 开始根据条件{}修改角色和菜单关联,", sysrolemenu);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int updated = sysrolemenuDao.updateById(sysrolemenu);
        resData.setData("updated", updated);
        log.info("###[服务] 完成修改角色和菜单关联，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData delete(String menuid, String roleid) throws Exception {
        log.debug("###[服务] 开始根据条件{}删除角色和菜单关联,", menuid, roleid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        SysRoleMenu sysrolemenu = new SysRoleMenu();
        sysrolemenu.setMenuid(Long.valueOf(menuid));
        sysrolemenu.setRoleid(Long.valueOf(roleid));
        int deleted = sysrolemenuDao.deleteById(sysrolemenu);
        resData.setData("deleted", deleted);
        log.info("###[服务] 完成删除角色和菜单关联，ResultData=[{}]", resData);
        return resData;
    }
}
