package com.rufeng.business.system.service.impl;


import java.util.List;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;

import com.rufeng.core.framework.db.Pager;
import com.rufeng.core.framework.web.ResultData;
import com.rufeng.business.system.service.ISysRoleDeptService;
import com.rufeng.business.system.mapper.ISysRoleDeptDao;
import com.rufeng.business.system.domain.po.SysRoleDept;


/**
 * 角色和部门关联 服务接口实现
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@Service
public class SysRoleDeptServiceImpl extends ServiceImpl<ISysRoleDeptDao,SysRoleDept> implements ISysRoleDeptService {
    private Logger log = LoggerFactory.getLogger(SysRoleDeptServiceImpl.class);

    @Autowired
    private ISysRoleDeptDao sysroledeptDao;

    @Override
    public ResultData get(String deptid, String roleid) throws Exception {
        log.debug("###[服务] 开始查询角色和部门关联 deptid=[{}]. roleid=[{}]. ", deptid, roleid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
//        Map<String, String> param = new HashMap<String, String>();
//        param.put("deptid", deptid);
//        param.put("roleid", roleid);
//        SysRoleDept sysroledept = sysroledeptDao.get(param);
//        resData.setData("sysroledept", sysroledept);
        log.info("###[服务] 完成查询角色和部门关联 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData find(SysRoleDept sysroledept) throws Exception {
        log.debug("###[服务] 开始根据条件{}查询角色和部门关联", sysroledept);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        QueryWrapper<SysRoleDept> sysroledeptWrapper = new QueryWrapper<>();
        sysroledeptWrapper.setEntity(sysroledept);
        List<SysRoleDept> sysroledepts = sysroledeptDao.selectList(sysroledeptWrapper);
        resData.setData("sysroledepts", sysroledepts);
        log.info("###[服务] 完成查询角色和部门关联 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData listPager(SysRoleDept sysroledept, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询角色和部门关联", sysroledept);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        Page<SysRoleDept> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysRoleDept> sysroledeptWrapper = new QueryWrapper<>();
        sysroledeptWrapper.setEntity(sysroledept);
        IPage<SysRoleDept> pu = sysroledeptDao.selectPage(pageParam, sysroledeptWrapper);
        resData.setData("data", pu);

        log.info("###[服务] 完成分页查询角色和部门关联 resData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData add(SysRoleDept sysroledept) throws Exception {
        log.debug("###[服务] 开始添加新角色和部门关联, {}", sysroledept);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int inserted = sysroledeptDao.insert(sysroledept);
        resData.setData("inserted", inserted);
        log.info("###[服务] 完成添加新角色和部门关联，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData update(SysRoleDept sysroledept) throws Exception {
        log.debug("###[服务] 开始根据条件{}修改角色和部门关联,", sysroledept);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int updated = sysroledeptDao.updateById(sysroledept);
        resData.setData("updated", updated);
        log.info("###[服务] 完成修改角色和部门关联，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData delete(String deptid, String roleid) throws Exception {
        log.debug("###[服务] 开始根据条件{}删除角色和部门关联,", deptid, roleid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        SysRoleDept sysroledept = new SysRoleDept();
        sysroledept.setDeptid(Long.valueOf(deptid));
        sysroledept.setRoleid(Long.valueOf(roleid));
        int deleted = sysroledeptDao.deleteById(sysroledept);
        resData.setData("deleted", deleted);
        log.info("###[服务] 完成删除角色和部门关联，ResultData=[{}]", resData);
        return resData;
    }
}
