package com.rufeng.business.system.service.impl;


import java.util.List;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;

import com.rufeng.core.framework.db.Pager;
import com.rufeng.core.framework.web.ResultData;
import com.rufeng.business.system.service.ISysUserPostService;
import com.rufeng.business.system.mapper.ISysUserPostDao;
import com.rufeng.business.system.domain.po.SysUserPost;


/**
 * 用户与岗位关联 服务接口实现
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@Service
public class SysUserPostServiceImpl extends ServiceImpl<ISysUserPostDao, SysUserPost> implements ISysUserPostService {
    private Logger log = LoggerFactory.getLogger(SysUserPostServiceImpl.class);

    @Autowired
    private ISysUserPostDao sysuserpostDao;

    @Override
    public ResultData get(String postid, String userid) throws Exception {
        log.debug("###[服务] 开始查询用户与岗位关联 postid=[{}]. userid=[{}]. ", postid, userid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
//        Map<String, String> param = new HashMap<String, String>();
//        param.put("postid", postid);
//        param.put("userid", userid);
//        SysUserPost sysuserpost = sysuserpostDao.get(param);
//        resData.setData("sysuserpost", sysuserpost);
        log.info("###[服务] 完成查询用户与岗位关联 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData find(SysUserPost sysuserpost) throws Exception {
        log.debug("###[服务] 开始根据条件{}查询用户与岗位关联", sysuserpost);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        QueryWrapper<SysUserPost> sysuserpostWrapper = new QueryWrapper<>();
        sysuserpostWrapper.setEntity(sysuserpost);
        List<SysUserPost> sysuserposts = sysuserpostDao.selectList(sysuserpostWrapper);
        resData.setData("sysuserposts", sysuserposts);
        log.info("###[服务] 完成查询用户与岗位关联 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData listPager(SysUserPost sysuserpost, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询用户与岗位关联", sysuserpost);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        Page<SysUserPost> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysUserPost> sysuserpostWrapper = new QueryWrapper<>();
        sysuserpostWrapper.setEntity(sysuserpost);
        IPage<SysUserPost> pu = sysuserpostDao.selectPage(pageParam, sysuserpostWrapper);
        resData.setData("data", pu);

        log.info("###[服务] 完成分页查询用户与岗位关联 resData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData add(SysUserPost sysuserpost) throws Exception {
        log.debug("###[服务] 开始添加新用户与岗位关联, {}", sysuserpost);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int inserted = sysuserpostDao.insert(sysuserpost);
        resData.setData("inserted", inserted);
        log.info("###[服务] 完成添加新用户与岗位关联，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData update(SysUserPost sysuserpost) throws Exception {
        log.debug("###[服务] 开始根据条件{}修改用户与岗位关联,", sysuserpost);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int updated = sysuserpostDao.updateById(sysuserpost);
        resData.setData("updated", updated);
        log.info("###[服务] 完成修改用户与岗位关联，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData delete(String postid, String userid) throws Exception {
        log.debug("###[服务] 开始根据条件{}删除用户与岗位关联,", postid, userid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        SysUserPost sysuserpost = new SysUserPost();
        sysuserpost.setPostid(Long.valueOf(postid));
        sysuserpost.setUserid(Long.valueOf(userid));
        int deleted = sysuserpostDao.deleteById(sysuserpost);
        resData.setData("deleted", deleted);
        log.info("###[服务] 完成删除用户与岗位关联，ResultData=[{}]", resData);
        return resData;
    }
}
