package com.rufeng.business.system.controller;


import com.rufeng.business.system.domain.po.SysLogininfor;
import com.rufeng.business.system.service.ISysLogininforService;
import com.rufeng.core.framework.web.ResultData;
import com.rufeng.core.framework.db.Pager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;


/**
 * 系统访问记录控制器
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@RestController
@RequestMapping("/system/syslogininfor")
public class SysLogininforController {
    private Logger log = LoggerFactory.getLogger(SysLogininforController.class);

    @Autowired
    private ISysLogininforService syslogininforService;

    /**
     * 获取系统访问记录
     *
     * @param info_id 访问ID
     * @return ResultData
     */
    @RequestMapping(value = "/get/{info_id}", method = {RequestMethod.GET})
    public ResultData get(@PathVariable String info_id) throws Exception {
        log.debug("###开始查询系统访问记录， info_id=[{}].", info_id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return syslogininforService.get(info_id);
    }

    /**
     * 查询系统访问记录
     *
     * @param syslogininfor 系统访问记录对象
     * @return ResultData
     */
    @RequestMapping(value = "/list", method = {RequestMethod.POST})
    public ResultData list(SysLogininfor syslogininfor) throws Exception {
        log.debug("###开始根据条件{}查询系统访问记录", syslogininfor);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return syslogininforService.list(syslogininfor);
    }


    /**
     * 分页查询系统访问记录
     *
     * @param page          分页对象
     * @param syslogininfor 系统访问记录对象
     * @return ResultData
     */
    @RequestMapping(value = "/list-by-page", method = {RequestMethod.GET})
    public ResultData listPager(SysLogininfor syslogininfor, Pager page) throws Exception {
        log.debug("###开始根据条件{}分页查询系统访问记录", syslogininfor);
        return syslogininforService.listPager(syslogininfor, page);
    }

    /**
     * 删除系统访问记录
     *
     * @param info_id 访问ID
     * @return ResultData
     */
    @RequestMapping(value = "/delete/{id}", method = {RequestMethod.DELETE})
    public ResultData delete(String info_id) throws Exception {
        log.debug("###开始删除系统访问记录对象，info_id={}.", info_id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return syslogininforService.delete(info_id);
    }

    /**
     * 清空系统访问记录对象
     *
     * @return
     */
    @RequestMapping(value = "/clean", method = {RequestMethod.DELETE})
    public ResultData clean() {
        log.debug("###开始清空系统访问记录对象");
        return syslogininforService.cleanLogininfor();
    }
}