package com.rufeng.business.system.controller;


import com.rufeng.business.system.domain.po.SysMenu;
import com.rufeng.business.system.service.ISysMenuService;
import com.rufeng.core.framework.aspectj.lang.annotation.Log;
import com.rufeng.core.framework.aspectj.lang.enums.BusinessType;
import com.rufeng.core.framework.security.LoginUser;
import com.rufeng.core.framework.security.service.TokenService;
import com.rufeng.core.framework.web.ResultData;
import com.rufeng.core.framework.db.Pager;
import com.rufeng.core.utils.ServletUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * 菜单权限控制器
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@RestController
@RequestMapping("/system/sysmenu")
public class SysMenuController {
    private Logger log = LoggerFactory.getLogger(SysMenuController.class);

    @Autowired
    private ISysMenuService sysmenuService;
    @Autowired
    private TokenService tokenService;


    /**
     * 获取菜单权限
     *
     * @param menu_id 菜单ID
     * @return ResultData
     */
    @RequestMapping(value = "/get/{menu_id}", method = {RequestMethod.GET})
    public ResultData get(@PathVariable String menu_id) throws Exception {
        log.debug("###开始查询菜单权限， menu_id=[{}].", menu_id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysmenuService.get(menu_id);
    }

    /**
     * 查询菜单权限
     *
     * @param sysmenu 菜单权限对象
     * @return ResultData
     */
    @RequestMapping(value = "/list", method = {RequestMethod.GET})
    public ResultData list(SysMenu sysmenu) throws Exception {
        log.debug("###开始根据条件{}查询菜单权限", sysmenu);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysmenuService.list(sysmenu);
    }


    /**
     * 分页查询菜单权限
     *
     * @param page    分页对象
     * @param sysmenu 菜单权限对象
     * @return ResultData
     */
    @RequestMapping(value = "/list-by-page", method = {RequestMethod.GET})
    public ResultData listPager(SysMenu sysmenu, Pager page) throws Exception {
        log.debug("###开始根据条件{}分页查询菜单权限", sysmenu);
        return sysmenuService.listPager(sysmenu, page);
    }

    /**
     * 添加菜单权限
     *
     * @param sysmenu 菜单权限对象
     * @return ResultData
     */
    @Log(title = "添加菜单权限", businessType = BusinessType.INSERT)
    @RequestMapping(value = "/add", method = {RequestMethod.POST})
    public ResultData add(@RequestBody SysMenu sysmenu) throws Exception {
        log.debug("###开始查找添加菜单权限， [{}]", sysmenu);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysmenuService.add(sysmenu);
    }

    /**
     * 更新菜单权限
     *
     * @param sysmenu 菜单权限对象
     * @return ResultData
     */
    @Log(title = "更新菜单权限", businessType = BusinessType.UPDATE)
    @RequestMapping(value = "/update", method = {RequestMethod.PUT})
    public ResultData update(@RequestBody SysMenu sysmenu) throws Exception {
        log.debug("###开始修改菜单权限， [{}]", sysmenu);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysmenuService.update(sysmenu);
    }

    /**
     * 删除菜单权限
     *
     * @param menu_id 菜单ID
     * @return ResultData
     */
    @Log(title = "删除菜单权限", businessType = BusinessType.DELETE)
    @RequestMapping(value = "/delete/{menu_id}", method = {RequestMethod.DELETE})
    public ResultData delete(@PathVariable String menu_id) throws Exception {
        log.debug("###开始删除菜单权限对象，menu_id={}.", menu_id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysmenuService.delete(menu_id);
    }

    /**
     * 获取菜单下拉树列表
     */
    @RequestMapping(value = "/treeselect", method = {RequestMethod.GET})
    public ResultData treeselect(SysMenu menu) {
        LoginUser loginUser = tokenService.getLoginUser(ServletUtils.getRequest());
        Long userId = loginUser.getUser().getUserid();
        List<SysMenu> menus = sysmenuService.selectMenuList(menu, userId);
        return sysmenuService.buildMenuTreeSelect(menus);
    }

    /**
     * 加载对应角色菜单列表树
     */
    @RequestMapping(value = "/roleMenuTreeselect/{roleId}", method = {RequestMethod.GET})
    public ResultData roleMenuTreeselect(@PathVariable("roleId") Long roleId) {
        ResultData data = ResultData.init();
        LoginUser loginUser = tokenService.getLoginUser(ServletUtils.getRequest());
        List<SysMenu> menus = sysmenuService.selectMenuList(loginUser.getUser().getUserid());
        data.setData("checkedKeys", sysmenuService.selectMenuListByRoleId(roleId));
        data.setData("menus", sysmenuService.buildMenuTreeSelect(menus).getData().get("menuTrees"));
        return data;
    }

}