package com.rufeng.business.system.controller;


import com.rufeng.business.system.domain.po.SysOperLog;
import com.rufeng.business.system.service.ISysOperLogService;
import com.rufeng.core.framework.web.ResultData;
import com.rufeng.core.framework.db.Pager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;


/**
 * 操作日志记录控制器
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@RestController
@RequestMapping("/system/sysoperlog")
public class SysOperLogController {
    private Logger log = LoggerFactory.getLogger(SysOperLogController.class);

    @Autowired
    private ISysOperLogService sysoperlogService;

    /**
     * 获取操作日志记录
     *
     * @param oper_id 日志主键
     * @return ResultData
     */
    @RequestMapping(value = "/get/{oper_id}", method = {RequestMethod.GET})
    public ResultData get(@PathVariable String oper_id) throws Exception {
        log.debug("###开始查询操作日志记录， oper_id=[{}].", oper_id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysoperlogService.get(oper_id);
    }

    /**
     * 查询操作日志记录
     *
     * @param sysoperlog 操作日志记录对象
     * @return ResultData
     */
    @RequestMapping(value = "/list", method = {RequestMethod.GET})
    public ResultData list(SysOperLog sysoperlog) throws Exception {
        log.debug("###开始根据条件{}查询操作日志记录", sysoperlog);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysoperlogService.list(sysoperlog);
    }


    /**
     * 分页查询操作日志记录
     *
     * @param page       分页对象
     * @param sysoperlog 操作日志记录对象
     * @return ResultData
     */
    @RequestMapping(value = "/list-by-page", method = {RequestMethod.GET})
    public ResultData listPager(SysOperLog sysoperlog, Pager page) throws Exception {
        log.debug("###开始根据条件{}分页查询操作日志记录", sysoperlog);
        return sysoperlogService.listPager(sysoperlog, page);
    }

    /**
     * 添加操作日志记录
     *
     * @param sysoperlog 操作日志记录对象
     * @return ResultData
     */
    @RequestMapping(value = "/add", method = {RequestMethod.POST})
    public ResultData add(@RequestBody SysOperLog sysoperlog) throws Exception {
        log.debug("###开始查找添加操作日志记录， [{}]", sysoperlog);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysoperlogService.add(sysoperlog);
    }

    /**
     * 更新操作日志记录
     *
     * @param sysoperlog 操作日志记录对象
     * @return ResultData
     */
    @RequestMapping(value = "/update", method = {RequestMethod.PUT})
    public ResultData update(@RequestBody SysOperLog sysoperlog) throws Exception {
        log.debug("###开始修改操作日志记录， [{}]", sysoperlog);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysoperlogService.update(sysoperlog);
    }

    /**
     * 删除操作日志记录
     *
     * @param oper_id 日志主键
     * @return ResultData
     */
    @RequestMapping(value = "/delete/{oper_id}", method = {RequestMethod.DELETE})
    public ResultData delete(@PathVariable String oper_id) throws Exception {
        log.debug("###开始删除操作日志记录对象，oper_id={}.", oper_id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysoperlogService.delete(oper_id);
    }
}