package com.rufeng.business.system.controller;


import com.rufeng.business.system.domain.po.SysPost;
import com.rufeng.business.system.service.ISysPostService;
import com.rufeng.core.framework.aspectj.lang.annotation.Log;
import com.rufeng.core.framework.aspectj.lang.enums.BusinessType;
import com.rufeng.core.framework.web.ResultData;
import com.rufeng.core.framework.db.Pager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;


/**
 * 岗位信息控制器
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@RestController
@RequestMapping("/system/syspost")
public class SysPostController {
    private Logger log = LoggerFactory.getLogger(SysPostController.class);

    @Autowired
    private ISysPostService syspostService;

    /**
     * 获取岗位信息
     *
     * @param post_id 岗位ID
     * @return ResultData
     */
    @RequestMapping(value = "/get/{post_id}", method = {RequestMethod.GET})
    public ResultData get(@PathVariable String post_id) throws Exception {
        log.debug("###开始查询岗位信息， post_id=[{}].", post_id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return syspostService.get(post_id);
    }

    /**
     * 查询岗位信息
     *
     * @param syspost 岗位信息对象
     * @return ResultData
     */
    @RequestMapping(value = "/list", method = {RequestMethod.GET})
    public ResultData list(SysPost syspost) throws Exception {
        log.debug("###开始根据条件{}查询岗位信息", syspost);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return syspostService.list(syspost);
    }


    /**
     * 分页查询岗位信息
     *
     * @param page    分页对象
     * @param syspost 岗位信息对象
     * @return ResultData
     */
    @RequestMapping(value = "/list-by-page", method = {RequestMethod.GET})
    public ResultData listPager(SysPost syspost, Pager page) throws Exception {
        log.debug("###开始根据条件{}分页查询岗位信息", syspost);
        return syspostService.listPager(syspost, page);
    }

    /**
     * 添加岗位信息
     *
     * @param syspost 岗位信息对象
     * @return ResultData
     */
    @Log(title = "添加岗位信息", businessType = BusinessType.INSERT)
    @RequestMapping(value = "/add", method = {RequestMethod.POST})
    public ResultData add(@RequestBody SysPost syspost) throws Exception {
        log.debug("###开始查找添加岗位信息， [{}]", syspost);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return syspostService.add(syspost);
    }

    /**
     * 更新岗位信息
     *
     * @param syspost 岗位信息对象
     * @return ResultData
     */
    @Log(title = "更新岗位信息", businessType = BusinessType.UPDATE)
    @RequestMapping(value = "/update", method = {RequestMethod.PUT})
    public ResultData update(@RequestBody SysPost syspost) throws Exception {
        log.debug("###开始修改岗位信息， [{}]", syspost);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return syspostService.update(syspost);
    }

    /**
     * 删除岗位信息
     *
     * @param post_id 岗位ID
     * @return ResultData
     */
    @Log(title = "删除岗位信息", businessType = BusinessType.DELETE)
    @RequestMapping(value = "/delete/{post_id}", method = {RequestMethod.DELETE})
    public ResultData delete(@PathVariable String post_id) throws Exception {
        log.debug("###开始删除岗位信息对象，post_id={}.", post_id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return syspostService.delete(post_id);
    }
}