package com.rufeng.business.system.controller;


import com.rufeng.business.system.domain.po.SysRole;
import com.rufeng.business.system.service.ISysRoleService;
import com.rufeng.core.framework.aspectj.lang.annotation.Log;
import com.rufeng.core.framework.aspectj.lang.enums.BusinessType;
import com.rufeng.core.framework.web.ResultData;
import com.rufeng.core.framework.db.Pager;
import com.rufeng.core.utils.SecurityUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;


/**
 * 角色信息控制器
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@RestController
@RequestMapping("/system/sysrole")
public class SysRoleController {
    private Logger log = LoggerFactory.getLogger(SysRoleController.class);

    @Autowired
    private ISysRoleService sysroleService;

    /**
     * 获取角色信息
     *
     * @param role_id 角色ID
     * @return ResultData
     */
    @RequestMapping(value = "/get/{role_id}", method = {RequestMethod.GET})
    public ResultData get(@PathVariable String role_id) throws Exception {
        log.debug("###开始查询角色信息， role_id=[{}].", role_id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysroleService.get(role_id);
    }

    /**
     * 查询角色信息
     *
     * @param sysrole 角色信息对象
     * @return ResultData
     */
    @RequestMapping(value = "/list", method = {RequestMethod.GET})
    public ResultData find(SysRole sysrole) throws Exception {
        log.debug("###开始根据条件{}查询角色信息", sysrole);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysroleService.find(sysrole);
    }


    /**
     * 分页查询角色信息
     *
     * @param page    分页对象
     * @param sysrole 角色信息对象
     * @return ResultData
     */
    @RequestMapping(value = "/list-by-page", method = {RequestMethod.GET})
    public ResultData listPager(SysRole sysrole, Pager page) throws Exception {
        log.debug("###开始根据条件{}分页查询角色信息", sysrole);
        return sysroleService.listPager(sysrole, page);
    }

    /**
     * 添加角色信息
     *
     * @param sysrole 角色信息对象
     * @return ResultData
     */
    @Log(title = "添加角色信息", businessType = BusinessType.INSERT)
    @RequestMapping(value = "/add", method = {RequestMethod.POST})
    public ResultData add(@RequestBody SysRole sysrole) throws Exception {
        log.debug("###开始查找添加角色信息， [{}]", sysrole);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysroleService.add(sysrole);
    }

    /**
     * 更新角色信息
     *
     * @param sysrole 角色信息对象
     * @return ResultData
     */
    @Log(title = "更新角色信息", businessType = BusinessType.UPDATE)
    @RequestMapping(value = "/update", method = {RequestMethod.PUT})
    public ResultData update(@RequestBody SysRole sysrole) throws Exception {
        log.debug("###开始修改角色信息， [{}]", sysrole);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysroleService.update(sysrole);
    }

    /**
     * 删除角色信息
     *
     * @param roleIds 角色ID
     * @return ResultData
     */
    @Log(title = "删除角色信息", businessType = BusinessType.DELETE)
    @RequestMapping(value = "/delete/{roleIds}", method = {RequestMethod.DELETE})
    public ResultData delete(@PathVariable Long[] roleIds) throws Exception {
        log.debug("###开始删除角色信息对象，role_id={}.", roleIds);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysroleService.deleteByIds(roleIds);
    }

    /**
     * 角色状态修改
     */
    @PutMapping("/changeStatus")
    @Log(title = "角色状态修改", businessType = BusinessType.UPDATE)
    public ResultData changeStatus(@RequestBody SysRole role) throws Exception {
        sysroleService.checkRoleAllowed(role);
        role.setUpdateby(SecurityUtils.getUsername());
        return sysroleService.updateRoleStatus(role);
    }
}