package com.rufeng.business.pms.controller;

import java.util.List;

import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import com.rufeng.core.framework.aspectj.lang.annotation.Log;
import com.rufeng.core.framework.aspectj.lang.enums.BusinessType;
import com.rufeng.core.framework.db.Pager;
import com.rufeng.core.framework.web.ResultData;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.rufeng.business.pms.domain.po.ProductCategory;
import com.rufeng.business.pms.service.IProductCategoryService;

/**
 * 产品分类Controller
 *
 * @author chg
 * @date 2021-03-11
 */
@RestController
@RequestMapping("/pms/category")
public class ProductCategoryController {
    private Logger log = LoggerFactory.getLogger(ProductCategoryController.class);
    @Autowired
    private IProductCategoryService productCategoryService;

    /**
     * 获取产品分类详细信息
     */
    @GetMapping(value = "get/{id}")
    public ResultData getInfo(@PathVariable("id") Long id) {
        log.debug("开始查询参数配置， id=[{}].", id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return productCategoryService.get(id);
    }


    /**
     * 查询产品分类列表
     */
    @RequestMapping(value = "/list", method = {RequestMethod.GET})
        public ResultData list(ProductCategory productCategory) {
        log.debug("开始根据条件{}查询参数配置, productCategory=[{}]", productCategory);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return productCategoryService.list(productCategory);
    }
    
    /**
     * 分页查询产品分类列表
     */
    @RequestMapping(value = "/list-by-page", method = {RequestMethod.GET})
        public ResultData listPager(ProductCategory productCategory, Pager page) {
        log.debug("开始根据条件{}分页查询参数配置, productCategory=[{}]",productCategory);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return productCategoryService.listPager(productCategory, page);
    }
    
    /**
     * 新增产品分类
     */
    @Log(title = "新增产品分类", businessType = BusinessType.INSERT)
    @RequestMapping(value = "/add", method = {RequestMethod.POST})
    public ResultData add(@RequestBody ProductCategory productCategory) {
        log.debug("开始添加新增产品分类，productCategory=[{}]", productCategory);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return productCategoryService.add(productCategory);
    }

    /**
     * 修改产品分类
     */
    @Log(title = "产品分类", businessType = BusinessType.UPDATE)
    @RequestMapping(value = "/update", method = {RequestMethod.PUT})
    public ResultData edit(@RequestBody ProductCategory productCategory) {
        log.debug("开始修改参数配置， productCategory=[{}]", productCategory);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return productCategoryService.update(productCategory);
    }

    /**
     * 删除产品分类
     */
    @Log(title = "产品分类", businessType = BusinessType.DELETE)
    @RequestMapping(value = "/delete/{id}", method = {RequestMethod.DELETE})
    public ResultData remove(@PathVariable Long id) {
        log.debug("开始删除产品分类对象，id={}.", id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return productCategoryService.delete(id);
    }
}
